import Navbar from "@/components/Navbar";
import "./globals.css";
import connectDB from "@/services/mongo";

export const metadata = 
  {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export  default async function RootLayout({ children }) 
  {
    await connectDB();
    return (
      <html lang="en">
        <body>
          <Navbar />
          <main className="py-8">
            {children}
          </main>
        </body>
      </html>
    );
  }
